name: marina
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  go_router: ^15.2.0
  lottie: ^3.3.1
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Jura
      fonts:
        - asset: assets/fonts/Jura-Bold.ttf
        - asset: assets/fonts/Jura-SemiBold.ttf
        - asset: assets/fonts/Jura-Medium.ttf
        - asset: assets/fonts/Jura-Regular.ttf
        - asset: assets/fonts/Jura-Light.ttf
